# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Bitmonk
tagline:          1% better everyday
url:              http://www.thebitmonk.com
shorturl:         thebitmonk.com

author:
  name:           'Varun Jain'
  url:            https://twitter.com/rebelvarun

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/thebitmonk/thebitmonk.github.io


# This is the list of pages to incldue in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
